### PR TITLE
Harmonization with OGC API Processes

### LINKED ISSUE #15: 'Processes' Section Options
Having a Profile of Processes as a second API in the current document may be confusing to the geospatial community. The Routes SWG recommends on 23 Feb 2021 that a path forward may be one of the following options...

1 Keep it as a separate, optional Conformance Class of Part 1 of the OGC API - Routes

2 Move it to a new Part 2 of OGC API - Routes

3 Develop a separate document on how to implement Routes with OGC API - Processes

Please provide your comments and feedback on this Issue to inform the SWG.

### LINKED ISSUE #17: Can we make the RAPI request identical to a Processes Execute Request?
Given that several steps have been taken in _OGC API - Processes_ to simplify and make more concise execution requests, could the routing API go the extra step to harmonize the routing requests, whether implemented as a stand-alone _Routes API_, or integrated within an _OGC API - Processes_ service?

This would make it possible for generic _OGC API - Processes_ clients to access _OGC API - Routes_ services only implementing Part 1, providing they could be used with a separate generic routing process description.

The only remaining required changes would be:
- embedding the routing request parameters inside an `inputs` object property, and
- wrapping values inside an object with a `value` property

This would mean going from:
```json
{
  "waypoints":
  {
    "type": "MultiPoint",
    "coordinates": [
       [ 36.1234515, 32.6453783 ],
       [ 36.1214698, 32.655952  ],
       [ 36.1247213, 32.7106286 ]
   ]
  },
  "preference" : "fastest",
  "height" : 4.5
}
```

to:
```json
{
  "inputs": {
    "waypoints":
    {
      "value": {
        "type": "MultiPoint",
        "coordinates": [
          [ 36.1234515, 32.6453783 ],
          [ 36.1214698, 32.655952  ],
          [ 36.1247213, 32.7106286 ]
        ]
      }
    },
    "preference" : { "value": "fastest" },
    "height" : { "value": 4.5 }
  }
}
```

My own opinion is that this is now a small cost to pay in terms of simplicity and elegance, for the interoperability benefits and avoiding the situation of having two different competing routing APIs.

### PR DESCRIPTION
**Pull request by cportele**
This pull request closes #15 and closes #17.

### CODE REVIEW

**Comment by cportele** [comment]
I cannot add you as a reviewer @jerstlouis, so I mention you in this comment: please have a look.

**Comment by jerstlouis** [comment]
Thanks @cportele 
I really have been struggling going back & forth in my mind about the need for this extra `"value"`.
Thinking that this will also be needed for a _Maps_ extension allowing to specify custom inline styles object (profile of _Processes_, similar to _Routes_).

Then I read @fmigneault 's comments again and I think the most convincing arguments for the extra `"value"` (as opposed to trying to figure out a way to disembiguate pre-defined object schemas that can be substituted for it) is [this comment](https://github.com/opengeospatial/ogcapi-processes/issues/183#issuecomment-840879117), specifically:

>  Imagine JSON spec did the same, that they allowed you to write any schema, except you are not allowed to use a field named type because they use it internally to define their schema. Wouldn't it feel wrong?

> The value adds that sub-object where we can safely tell the user: "do whatever you want in there, its your own schema". 

and I think we took the right decision after all.

I had the look at the pull request and it looks good so far. After this is merge, I will have another go at updating the _processes_ section in light of more recent changes to the process description (e.g. the switch from `literalDataDomain`/`formats` to JSON Schema for describing, and from "id" to key / values for, both inputs & outputs).

**Comment by cportele** [comment]
Thanks @jerstlouis. 

For Routes the "value" and "inputs" wrappers do not add any value, they just add noise. This seems to be different for Processes, because of the resource design in that standard.

I still have doubts that it is the right decision to add the wrappers in Routes, too, because in general Routes and Processes are separate resources and there is a trivial mapping/conversion for those that want to implement Routing using a Processes backend, but I accept that we add them in order to move forward with both Routes and Processes.

**Comment by jeffharrison** [comment]
Please note - We will have this Issue as an Agenda Item for the SWG meeting.

**Comment by jeffharrison** [comment]
16 June 2021 SWG Meeting discussed this PR. There were comments and discussions as to whether this addition adds too much 'noise' to the API. Key points are that it does not affect Route Exchange Model (REM) and it also does not 'break' the API in the opinion of SWG members. Members requested a specific Use Case where this is used.  Response was to support a client that supports only Routes API and a 'generic' client that support Processes API.  Question brought up... Can this be added later? Answer is No. This is a 'Do now or never' decision. Observation made that we are not developing a Processes profile. Adding this elements closes an 'enormous gap' between Routes resource approach and Processes resource approach. Attendees noted the cost is small with respect to adding this, and there may be benefits. 

Caveat 1 - Would it help if a note was added to explain why we have these elements? Yes. Very important to include this before or as we merge. 

The Use Case is to allow both generic Processes client and Routes client to function with API. 

NOTUC to Merging this PR.

**Pull request merged**
